title: DeskAIer Wiki
description: DeskAIer documentation (Japanese / English)
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Disable minima auto mixed nav menu
header_pages:
  - _none.md
